baseurl = "/"
languageCode = "en-us"
title = "Alana Higgins"
theme = "mediumish-gohugo-theme"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Projects"
    url = "/projects/"
[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/alana-higgins-2019/"
[[menu.main]]
    name = "How I Build This Website"
    url = "/aboutwebsite/"

[params]
    description = "A digital portfolio of environmental geospatial and remote sensing work."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"
    
[params.logo]
  url = "initials.png"
  width = 50
  height = 50
  alt = "Logo"

