baseurl = "/"
languageCode = "en-us"
title = "Alana Higgins"
theme = "hugo-theme-cleanwhite"
googleAnalytics = ""
disqusShortname = ""
paginate = 15 #frontpage pagination
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[menu]

 [[params.addtional_menus]]
  title =  "Project Catalog"
  href =  "/top/projectcat/"
  
  [[params.addtional_menus]]
  title =  "how i built this website"
  href =  "/top/aboutwebsite/"
  
  [[params.addtional_menus]]
  title = "Contact"
  href = "/top/contact/"

    
[params]    
header_image = "img/home.jpg"
slogan = "A digital portfolio of environmental, geospatial, and remote sensing work."
sidebar_about_description = "Environmental enthusiast, geospatial analyst, and community activist"



    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

