baseurl = "/"
languageCode = "en-us"
title = "Alana Higgins"
theme = "hugo-theme-cleanwhite"
googleAnalytics = ""
disqusShortname = ""
paginate = 8 #frontpage pagination
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[menu]
  [[params.addtional_menus]]
  title =  "about"
  href =  "/top/about/"
  image = "images/aesas.jpg"
  
  [[params.addtional_menus]]
  title =  "resume"
  href =  "/top/resume/"
  
  [[params.addtional_menus]]
  title =  "how i built this website"
  href =  "/top/aboutwebsite/"
  
    
[params]    
header_image = "img/home.jpg"
slogan = "A digital portfolio of environmental geospatial and remote sensing work."


    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

